#!/bin/bash

#
# Copyright © 2014 Peque
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.
#

for file in $(cat TODO.en.reset | grep ??? | sed -e 's/.*???\ \([^\ ]*\)\ .*/\1/' | tail -n +4); do
	./lolscript /en/$file;
	./lolscript /es/$file;
done

